### ISSUE TITLE
Search request handler: %-char inside search term produces error

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#120]
`2012-09-25 22:42:37 ERROR (WebloungeDispatcherServlet:374) URLDecoder: Incomplete trailing escape (%) pattern
java.lang.IllegalArgumentException: URLDecoder: Incomplete trailing escape (%) pattern
    at java.net.URLDecoder.decode(URLDecoder.java:187)
    at ch.entwine.weblounge.common.impl.request.RequestUtils.getParameter(RequestUtils.java:238)
    at ch.entwine.weblounge.common.impl.request.RequestUtils.getRequiredParameter(RequestUtils.java:333)
    at ch.entwine.weblounge.dispatcher.impl.handler.SearchRequestHandlerImpl.service(SearchRequestHandlerImpl.java:147)
    at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:353)
`

Probably we don't need to decode the parameter value in `RequestUtils.getParameter(..)` since this is already done in `request.getParameter(..)`

**Comment by ghost** [comment]
The search terms need to be properly escaped prior to being sent to Elasticsearch, as there are a number of special characters with % being one of them.

**Comment by ghost** [comment]
And yes, the parameters only need to be url decoded if they come in via a GET request.

**Comment by ghost** [comment]
2012-10-23 15:39:20 ERROR (WebloungeDispatcherServlet:370) Request handler 'search request handler' failed to handle /weblounge-search/ (187622) limit=15;query=kl%si;target-template=search-result
2012-10-23 15:39:20 ERROR (WebloungeDispatcherServlet:374) URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "si"
java.lang.IllegalArgumentException: URLDecoder: Illegal hex characters in escape (%) pattern - For input string: "si"
        at java.net.URLDecoder.decode(URLDecoder.java:192)
        at ch.entwine.weblounge.common.impl.request.RequestUtils.getParameter(RequestUtils.java:235)
        at ch.entwine.weblounge.common.impl.request.RequestUtils.getRequiredParameter(RequestUtils.java:330)
        at ch.entwine.weblounge.dispatcher.impl.handler.SearchRequestHandlerImpl.service(SearchRequestHandlerImpl.java:147)
        at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:353)

**Comment by ghost** [comment]
Added proper handling for non-URL-decoded parameters.
