### ISSUE TITLE
IllegalArgumentException in FeedRequestHandler

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#158]
`2012-11-14 13:14:17 ERROR (WebloungeDispatcherServlet:369) Request handler 'feed request handler' failed to handle /weblounge-feeds/rss/2.html (120454) subject=dnla
2012-11-14 13:14:17 ERROR (WebloungeDispatcherServlet:373) Language must not be null
java.lang.IllegalArgumentException: Language must not be null
        at ch.entwine.weblounge.common.impl.language.LocalizableContent.switchedTo(LocalizableContent.java:241)
        at ch.entwine.weblounge.common.impl.language.LocalizableObject.fireLanguageChanged(LocalizableObject.java:300)
        at ch.entwine.weblounge.common.impl.language.LocalizableObject.switchTo(LocalizableObject.java:282)
        at ch.entwine.weblounge.common.impl.language.LocalizableObject.switchTo(LocalizableObject.java:227)
        at ch.entwine.weblounge.dispatcher.impl.handler.FeedRequestHandlerImpl.createFeed(FeedRequestHandlerImpl.java:429)
        at ch.entwine.weblounge.dispatcher.impl.handler.FeedRequestHandlerImpl.service(FeedRequestHandlerImpl.java:240)
        at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:352)
`

**Comment by myniva** [comment]
I can reproduce this on our `production` and `staging` system, but not on my local `development` environment.
