### ISSUE TITLE
NPE in ImageResourceTag

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#159]
`2012-11-15 11:27:58  WARN (WebloungeTag:724) Error executing jsp tag ch.entwine.weblounge.taglib.resource.ImageResourceTag
java.lang.NullPointerException
        at ch.entwine.weblounge.taglib.resource.ImageResourceTag.doStartTag(ImageResourceTag.java:233)
        at org.apache.jsp.site.modules.repository.jsp.image.image_jsp._jspService(org.apache.jsp.site.modules.repository.jsp.image.image_jsp:176)
        at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:109)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)`

**Comment by myniva** [comment]
I cannot validate that my patch fixes this problem, since I don't know how to reproduce it. But it seems to be the most obvious reason for this kind of exception.
