### ISSUE TITLE
ConcurrentModificationException during startup

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#16]
```
2012-06-01 20:04:22 ERROR (SiteImpl:1201) Error loading module 'repository' of site rivellagames
2012-06-01 20:04:22 ERROR (?:?) [Swiss Unihockey Site Rivellagames] The activate method has thrown an exception
java.util.ConcurrentModificationException

at java.util.Hashtable$Enumerator.next(Hashtable.java:1048)
at ch.entwine.weblounge.common.impl.util.config.ConfigurationUtils.processTemplate(ConfigurationUtils.java:574)
at ch.entwine.weblounge.common.impl.util.config.ConfigurationUtils.processTemplate(ConfigurationUtils.java:634)
at ch.entwine.weblounge.common.impl.content.page.LinkImpl.setEnvironment(LinkImpl.java:170)
at ch.entwine.weblounge.common.impl.content.page.PageletRendererImpl.processURLTemplates(PageletRendererImpl.java:181)
at ch.entwine.weblounge.common.impl.content.page.PageletRendererImpl.setModule(PageletRendererImpl.java:117)
at ch.entwine.weblounge.common.impl.site.ModuleImpl.setSite(ModuleImpl.java:241)
at ch.entwine.weblounge.common.impl.site.SiteImpl.addModule(SiteImpl.java:618)
at ch.entwine.weblounge.common.impl.site.SiteImpl.activate(SiteImpl.java:1199)
```

**Comment by ghost** [comment]
It seems like iterating over System.getProperties() and System.getenv() needs a safety check.
