### ISSUE TITLE
NullPointerException caused by ImageRequestHandler

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#171]
2012-11-26 10:09:58 ERROR (WebloungeDispatcherServlet:369) Request handler 'image request handler' failed to handle /weblounge-images/1c075ed0-2766-463a-9a59-8c301d5d478b/index_en.html (1416) style=image-linklist
2012-11-26 10:09:58 ERROR (WebloungeDispatcherServlet:373) 
java.lang.NullPointerException
        at ch.entwine.weblounge.common.url.UrlUtils.isExtendedPrefix(UrlUtils.java:221)
        at ch.entwine.weblounge.contentrepository.impl.operation.MoveOperationImpl.apply(MoveOperationImpl.java:94)
        at ch.entwine.weblounge.contentrepository.impl.AbstractWritableContentRepository.get(AbstractWritableContentRepository.java:320)
        at ch.entwine.weblounge.dispatcher.impl.handler.ImageRequestHandlerImpl.service(ImageRequestHandlerImpl.java:167)
        at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:352)

**Comment by ghost** [comment]
This exception occured multiple times during system startup. It seems strange that there is a move operation going on.
