### ISSUE TITLE
ClassCastException in image request handler

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#180]
```
    2012-12-02 19:46:11 ERROR (WebloungeDispatcherServlet:367) ch.entwine.weblounge.common.impl.content.page.PageImpl cannot be cast to ch.entwine.weblounge.common.content.image.ImageResource
    java.lang.ClassCastException: ch.entwine.weblounge.common.impl.content.page.PageImpl cannot be cast to ch.entwine.weblounge.common.content.image.ImageResource
        at ch.entwine.weblounge.dispatcher.impl.handler.ImageRequestHandlerImpl.service(ImageRequestHandlerImpl.java:167)
        at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:346)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
        at org.apache.felix.http.base.internal.handler.ServletHandler.doHandle(ServletHandler.java:96)
        at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:79)
        at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:42)
        at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
        at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
```

**Comment by ghost** [comment]
Fixed
