### ISSUE TITLE
IllegalArgumentException in PageTAg

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#221]
Recently I saw this error message in our log files:

`2013-02-06 07:50:50  WARN (WebloungeTag:724) Error executing jsp tag ch.entwine.weblounge.taglib.resource.PageTag on /specials/masters/2012/forum/anmeldung/
2013-02-06 07:50:50  WARN (WebloungeTag:725) Language must not be null
java.lang.IllegalArgumentException: Language must not be null
    at ch.entwine.weblounge.common.impl.language.LocalizableObject.switchTo(LocalizableObject.java:247)
    at ch.entwine.weblounge.common.impl.language.LocalizableObject.switchTo(LocalizableObject.java:227)
    at ch.entwine.weblounge.common.impl.content.ResourceImpl.switchTo(ResourceImpl.java:948)
    at ch.entwine.weblounge.taglib.resource.PageTag.doStartTag(PageTag.java:129)
    at org.apache.jsp.site.modules.navigation.jsp.link.link_jsp._jspService(org.apache.jsp.site.modules.navigation.jsp.link.link_jsp:171)`

I don't understand how this error can occur since there's a null value check in `PageTag` on line 129

**Comment by ghost** [comment]
I agree, looking at the current doce, this is not possible. However, this part of the codebase has seen fixes just recently and the line numbers in ResourceImpl.switchTo() do not match anymore. I suggest closing this issue and reopening if it persists.
