### ISSUE TITLE
NPE during mail sending

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#24]
While sending an e-mail with the built-in smtp service, I got this NPE (maybe due to a miss-configured smtp service):

```
10:59:15 ERROR (ActionRequestHandlerImpl:388) 
java.lang.NullPointerException
    at org.apache.geronimo.javamail.transport.smtp.SMTPConnection.sendLine(SMTPConnection.java:666)
    at org.apache.geronimo.javamail.transport.smtp.SMTPConnection.sendCommand(SMTPConnection.java:654)
    at org.apache.geronimo.javamail.transport.smtp.SMTPConnection.sendQuit(SMTPConnection.java:571)
    at org.apache.geronimo.javamail.transport.smtp.SMTPConnection.close(SMTPConnection.java:181)
    at org.apache.geronimo.javamail.transport.smtp.SMTPTransport.close(SMTPTransport.java:503)
    at javax.mail.Transport.send0(Transport.java:191)
    at javax.mail.Transport.send(Transport.java:118)
    at ch.entwine.weblounge.kernel.mail.SmtpService.send(SmtpService.java:254)
    at ch.swissunihockey.weblounge.module.webservices.WebserviceRegistrationAction.sendMail(WebserviceRegistrationAction.java:471)
    at ch.swissunihockey.weblounge.module.webservices.WebserviceRegistrationAction.configure(WebserviceRegistrationAction.java:227)
    at ch.entwine.weblounge.dispatcher.impl.handler.ActionRequestHandlerImpl.serveHTML(ActionRequestHandlerImpl.java:344)
    at ch.entwine.weblounge.dispatcher.impl.handler.ActionRequestHandlerImpl.service(ActionRequestHandlerImpl.java:254)
    at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:353)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.apache.felix.http.base.internal.handler.ServletHandler.doHandle(ServletHandler.java:96)
    at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:79)
    at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:42)
    at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
    at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
    at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
    at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
    at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:326)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
    at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:943)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:756)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:218)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
    at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
    at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)
```

**Comment by ghost** [comment]
Basil, please add your smtp configuration (remember to remove passwords) and if possible a code snippet that shows how you are using the service.

**Comment by myniva** [comment]
My smtp service config:

```
mail.smtp.host=remote.swissunihockey.ch
mail.smtp.port=25
mail.user=basil.brunner
mail.password=********
mail.from=weblounge@localhost
```

Code

```
MimeMessage message = smtpService.createMessage();
message.addRecipient(RecipientType.TO, new InternetAddress(email, fullName));
message.addRecipient(RecipientType.BCC, new InternetAddress("mail@mail.com", "Bla Bla"));
message.setFrom(new InternetAddress("no-reply@swissunihockey.ch", "swiss unihockey"));
message.setSubject("Registration für '" + serviceName + "'");
message.setText(sb.toString(), "UTF-8");
smtpService.send(message);
```
