### ISSUE TITLE
IllegalArgumentException in PageRequestHandler

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#246]
`2013-03-18 18:06:58 ERROR (WebloungeDispatcherServlet:363) Request handler 'page request handler' failed to handle / (1719350) -
2013-03-18 18:06:58 ERROR (WebloungeDispatcherServlet:367) Cannot convert date: So, 17 Mrz 2013 17:47:31
java.lang.IllegalArgumentException: Cannot convert date: So, 17 Mrz 2013 17:47:31
        at org.mortbay.jetty.HttpFields.getDateField(HttpFields.java:832)
        at org.mortbay.jetty.Request.getDateHeader(Request.java:678)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.writeCacheEntry(CacheServiceImpl.java:677)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.startResponse(CacheServiceImpl.java:595)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.startResponse(CacheServiceImpl.java:542)
        at ch.entwine.weblounge.common.impl.request.WebloungeResponseImpl.startResponse(WebloungeResponseImpl.java:445)
        at ch.entwine.weblounge.dispatcher.impl.handler.PageRequestHandlerImpl.service(PageRequestHandlerImpl.java:293)
        at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:346)`

**Comment by ghost** [comment]
Duplicated by #250
