### ISSUE TITLE
IllegalArgumentException in FeedRequestHandler

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#247]
`2013-03-18 13:33:45 ERROR (WebloungeDispatcherServlet:363) Request handler 'feed request handler' failed to handle /weblounge-feeds/rss/2.html (1594410) -
2013-03-18 13:33:45 ERROR (WebloungeDispatcherServlet:367) Cannot convert date: "WL-13d5fa72798"
java.lang.IllegalArgumentException: Cannot convert date: "WL-13d5fa72798"
        at org.mortbay.jetty.HttpFields.getDateField(HttpFields.java:832)
        at org.mortbay.jetty.Request.getDateHeader(Request.java:678)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.writeCacheEntry(CacheServiceImpl.java:677)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.startResponse(CacheServiceImpl.java:595)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.startResponse(CacheServiceImpl.java:542)
        at ch.entwine.weblounge.common.impl.request.WebloungeResponseImpl.startResponse(WebloungeResponseImpl.java:445)
        at ch.entwine.weblounge.dispatcher.impl.handler.FeedRequestHandlerImpl.service(FeedRequestHandlerImpl.java:231)
        at ch.entwine.weblounge.dispatcher.impl.WebloungeDispatcherServlet.service(WebloungeDispatcherServlet.java:346)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:806)`

**Comment by ghost** [comment]
Duplicated by #250
