### ISSUE TITLE
Cache entry fails if the date header is malformed

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#249]
2013-04-02 12:08:13 ERROR (WebloungeDispatcherServlet:363) Request handler 'action request handler' failed to handle /spielbetrieb/liveticker/ajax/ (139229) amp;concour=;amp;league=;mode=quicklinks
2013-04-02 12:08:13 ERROR (WebloungeDispatcherServlet:367) Cannot convert date: Mo, 01 Apr 2013 15:17:06
java.lang.IllegalArgumentException: Cannot convert date: Mo, 01 Apr 2013 15:17:06
        at org.mortbay.jetty.HttpFields.getDateField(HttpFields.java:832)
        at org.mortbay.jetty.Request.getDateHeader(Request.java:678)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at javax.servlet.http.HttpServletRequestWrapper.getDateHeader(HttpServletRequestWrapper.java:75)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.writeCacheEntry(CacheServiceImpl.java:677)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.startResponse(CacheServiceImpl.java:595)
        at ch.entwine.weblounge.cache.impl.CacheServiceImpl.startResponse(CacheServiceImpl.java:542)
        at ch.entwine.weblounge.common.impl.request.WebloungeResponseImpl.startResponse(WebloungeResponseImpl.java:445)

**Comment by ghost** [comment]
Duplicated by #250
