### ISSUE TITLE
Intermittent error when shutting down endpoints

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#312]
^C14:02:44  INFO (SiteImpl:1396) Site 'weblounge-test' deactivated
ERROR: Bundle ch.entwine.weblounge.kernel [103] EventDispatcher: Error during dispatch. (java.lang.IllegalStateException: Invalid BundleContext.)
java.lang.IllegalStateException: Invalid BundleContext.
    at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:514)
    at org.apache.felix.framework.BundleContextImpl.getService(BundleContextImpl.java:449)
    at ch.entwine.weblounge.kernel.publisher.EndpointPublishingService$JSR311AnnotatedServiceListener.serviceChanged(EndpointPublishingService.java:331)
    at org.apache.felix.framework.util.EventDispatcher.invokeServiceListenerCallback(EventDispatcher.java:932)
    at org.apache.felix.framework.util.EventDispatcher.fireEventImmediately(EventDispatcher.java:793)
    at org.apache.felix.framework.util.EventDispatcher.fireServiceEvent(EventDispatcher.java:543)
    at org.apache.felix.framework.Felix.fireServiceEvent(Felix.java:4419)
    at org.apache.felix.framework.Felix.access$000(Felix.java:74)
    at org.apache.felix.framework.Felix$1.serviceChanged(Felix.java:401)
    at org.apache.felix.framework.ServiceRegistry.unregisterService(ServiceRegistry.java:151)
    at org.apache.felix.framework.ServiceRegistrationImpl.unregister(ServiceRegistrationImpl.java:127)
    at org.apache.felix.framework.ServiceRegistry.unregisterServices(ServiceRegistry.java:196)
    at org.apache.felix.framework.Felix.stopBundle(Felix.java:2555)
    at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1309)
    at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:304)
    at java.lang.Thread.run(Thread.java:695)

**Comment by ghost** [comment]
Closing, cannot reproduce anymore.
