### ISSUE TITLE
FileSystemContentRepositoryTest#testLock failed

### ISSUE THREAD

**Issue by myniva** [digitalroastery/weblounge#369]
```
ch.entwine.weblounge.contentrepository.fs.FileSystemContentRepositoryTest#testLock

java.lang.IllegalStateException: The page is already locked by
    at ch.entwine.weblounge.common.impl.content.ResourceImpl.lock(ResourceImpl.java:877)
    at ch.entwine.weblounge.contentrepository.impl.operation.LockOperationImpl.apply(LockOperationImpl.java:83)
    at ch.entwine.weblounge.contentrepository.impl.AbstractWritableContentRepository.get(AbstractWritableContentRepository.java:322)
    at ch.entwine.weblounge.contentrepository.impl.AbstractWritableContentRepository.isLocked(AbstractWritableContentRepository.java:464)
    at ch.entwine.weblounge.contentrepository.fs.FileSystemContentRepositoryTest.testLock(FileSystemContentRepositoryTest.java:917)
```

See https://travis-ci.org/entwinemedia/weblounge/jobs/47613732

**Comment by myniva** [comment]
Fixed by #382
