### ISSUE TITLE
Fix triggered() callback by Scheduler

### ISSUE THREAD

**Issue by ghost** [digitalroastery/weblounge#64]
3789 [DefaultQuartzScheduler_QuartzSchedulerThread] ERROR ch.o2it.weblounge.common.impl.scheduler.QuartzJobTrigger - Job implementation threw exception on trigger callback
java.lang.IllegalStateException: This trigger should be fired once only

at ch.o2it.weblounge.common.impl.scheduler.FireOnceJobTrigger.triggered(FireOnceJobTrigger.java:69)
at ch.o2it.weblounge.common.impl.scheduler.QuartzJobTrigger.triggered(QuartzJobTrigger.java:307)
at org.quartz.simpl.RAMJobStore.triggerFired(RAMJobStore.java:1217)
at org.quartz.core.QuartzSchedulerThread.run(QuartzSchedulerThread.java:308)

**Comment by ghost** [comment]
Turns out that the Quartz library is creating clones of triggers which then get called multiple times (twice, to be exact). So the solution seems to be to implement (clone()) on the QuartzJobTrigger class.
